### ISSUE TITLE
Can you help with tag emulation?

### ISSUE THREAD

**Issue by Tankonyako** [mywalkb/PN532#1]
Hello, im was looking for tag emulation for my pn532 with spi module, but all what im found - not working. my phone not detecting tag, reading tags with pn532 working. it also spamming with tgInitAsTarget failed or timed out!

**Comment by mywalkb** [comment]
Hello, I tested pn532 as tag emulation only with libnfc and was working.
I tested some examples of seeedstudio and all was working, I don't remember if I tested tag emulation.
When I will have some spare time, I will test.
Everytime I developed something for pn532 I always analyzed libnfc, try to see that library, it set all registers correctly.

**Comment by mywalkb** [comment]
I tested PN532/tree/arduino/PN532/examples/emulate_tag_ndef and partially works. I have not timeout on tgInitAsTarget but on my smartphone with android 11 the tag is detect as Felica with UID 00:00:00:00 while with another pn532 and libnfc I have:

```
nfc-list uses libnfc 1.8.0
NFC device: PN532 opened
1 ISO14443A passive target(s) found:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID3): 08  12  34  56  
      SAK (SEL_RES): 20  
                ATS: 75  33  92  03  
```
but sometimes in a loop (while :; do nfc-list ; sleep 1; done) detect 2 tags

```
nfc-list uses libnfc 1.8.0
NFC device: PN532 opened
1 ISO14443A passive target(s) found:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID3): 08  12  34  56  
      SAK (SEL_RES): 20  
                ATS: 75  33  92  03  

1 Felica (424 kbps) passive target(s) found:
FeliCa (424 kbps) target:
        ID (NFCID2): 00  00  00  00  00  00  00  00  
    Parameter (PAD): 00  00  00  00  00  00  00  00  
   System Code (SC): 00  00  
```
On android I used NFC Tools. If you want I can test your sketch on my environment.

**Comment by mywalkb** [comment]
Sorry my fault, I hadn't enabled debugging, now I see `tgInitAsTarget failed or timed out`
I tried to set the registers as in libnfc but for now I have not been successful.

**Comment by mywalkb** [comment]
I found a partial solution to issue, in loop there is nfc.emulate() without timeout so the default value is 0. The readResponse no have time to wait the reader and read response. 
I set 5000 ms and tgInitAsTarget not go in timeout when there is a reader which send data.

```
write:  8C 05 04 00 12 34 56 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
read:   8D 08 E0 50 // RATS
write:  86
read:   87 13
status is not ok
tgGetData failed!
```

There is however another problem, on android it only detects a Felica tag

**Comment by Tankonyako** [comment]
Hello, sorry for not responding. Im copy again your library and it working now! but my phone receive broken tag. 
![image](https://user-images.githubusercontent.com/48120579/173186310-7c69e2a0-402c-4f52-9f7c-c123957451b4.png)
![image](https://user-images.githubusercontent.com/48120579/173186313-e9d37626-d18a-4932-aa30-40c8ae5460b9.png)

**Comment by mywalkb** [comment]
> but my phone receive broken tag.

Hello, on this issue I'm still working. Tag emulation detect 2 tags, but android see only the wrong tag felica with uid 00:00:00.

**Comment by Tankonyako** [comment]
ah hello again maybe it caused because in emulatetag.cpp at 100 line command have too many zeros?

**Comment by mywalkb** [comment]
Sure you can set that bytes to a different value, but android detect always a felica. The command TgInitAsTarget has mandatory bytes.
I tested also libnfc examples (nfc-emulation-*) + android (as reader) and I got the same result.

With libnfc/examples/nfc-emulate-forum-tag2.c I got this

![IMG_20220611_142932](https://user-images.githubusercontent.com/66966897/173188020-76af58c4-b5ae-407c-b40c-1c7f3c16f1ed.jpg)

I'm porting on firmware

**Comment by Tankonyako** [comment]
if this will work is so good, i can sponsor you?

**Comment by mywalkb** [comment]
I released a new version of emulate_tag_ndef, now emulate a tag equal to libnfc/examples/nfc-emulate-forum-tag2
The tag is read only, but with some changes should be writable.
In this first release the code is in emulatetag.cpp, but I'd like move in sketch with callback.

**Comment by mywalkb** [comment]
Other update, now the target can be managed in the sketch.
nfc.emulate accept a callback function.

**Comment by Tankonyako** [comment]
im little confused, how to send ndef? and test writting?

**Comment by mywalkb** [comment]
I restored NDEF library, so now is more easy modify it.
For writing I have some issues. Android read a page after the user data and if it is not correctly formatted give write error, without try to write tag.

**Comment by Tankonyako** [comment]
im updated library, but receiving same empty response...

**Comment by Tankonyako** [comment]
```
#include "SPI.h"
#include "PN532_SPI.h"
#include "emulatetag.h"
#include "NdefMessage.h"

#define PN532_SCK  (14)
#define PN532_MOSI (13)
#define PN532_SS   (15)
#define PN532_MISO (12)

SPIClass nfcSPI(HSPI);
PN532_SPI pn532spi(SPI, 10);
EmulateTag    nfc(pn532spi);


uint8_t uid[3] = {0x12, 0x34, 0x56};
NdefMessage message;
int messageSize;

uint8_t memory_area[160];
/*= {
  0x00, 0x00, 0x00, 0x00,  // Block 0
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,  // Block 2 (Static lock bytes: CC area and data area are writeable)
  0xE1, 0x10, 0x06, 0x0F,  // Block 3 (CC - NFC-Forum Tag Type 2 version 1.0, Data area (from block 4 to the end) is 48 bytes, Read-only mode)
  0x03, 33,   0xd1, 0x02,  // Block 4 (NDEF)
  0x1c, 0x53, 0x70, 0x91,
  0x01, 0x09, 0x54, 0x02,
  0x65, 0x6e, 0x4c, 0x69,
  0x62, 0x6e, 0x66, 0x63,
  0x51, 0x01, 0x0b, 0x55,
  0x03, 0x6c, 0x69, 0x62,
  0x6e, 0x66, 0x63, 0x2e,
  0x6f, 0x72, 0x67, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
};*/

#define PAGESIZE 4
#define SIZE_USER_DATA sizeof(memory_area) - (4*PAGESIZE) // 4 page for header block 0 - 3

#define READ            0x30
#define WRITE           0xA2
#define SECTOR_SELECT   0xC2
#define HALT            0x50

void setup()
{
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Serial.println("------- Emulate Tag --------");
  
  nfcSPI.begin(PN532_SCK, PN532_MISO, PN532_MOSI, PN532_SS); 
  pn532spi = PN532_SPI(nfcSPI, PN532_SS);
  nfc = EmulateTag  (pn532spi);

  memset(memory_area, 0, sizeof(memory_area));

  // init CC to 144 bytes
  memory_area[0xC] = 0xE1;
  memory_area[0xD] = 0x10;
  memory_area[0xE] = 0x12;

  message = NdefMessage();
  message.addUriRecord("https://github.com/mywalkb");
  messageSize = message.getEncodedSize();
  if (messageSize > SIZE_USER_DATA)
  {
    Serial.println("userdata is too small");
    while (1);
  }

  Serial.print("Ndef encoded message size: ");
  Serial.println(messageSize);

  memory_area[0x10] = 3;
  memory_area[0x11] = messageSize;
  message.encode(&memory_area[0x12]);


  // uid must be 3 bytes!
  nfc.setUid(uid);

  nfc.init();
} 
void loop()
{
// uncomment for overriding ndef in case a write to this tag occured
  //nfc.setNdefFile(ndefBuf, messageSize);

  // start emulation (blocks)
  Serial.println(nfc.emulate(&processData, 5000));

  // or start emulation with timeout
  /*if(!nfc.emulate(1000)){ // timeout 1 second
      Serial.println("timed out");
    }*/

  // deny writing to the tag
  // nfc.setTagWriteable(false);

  delay(500);
 // scantag();
  delay(500);
}

uint8_t processData(const uint8_t *data_in, const size_t data_in_len, uint8_t *data_out, const size_t data_out_len)
{
    int8_t res = 0;

    switch (data_in[0]) {
      case READ:
        if (data_out_len >= 16) {
          if (data_in[1] >= (sizeof(memory_area)/4)) {
            memset(data_out, 0, 16);
          } else {
            memcpy(data_out, memory_area + (data_in[1] * 4), 16);
          }
          res = 16;
        } else {
          res = -1;
        }
        break;
      case WRITE:
        Serial.print("Write: ");
        Serial.println(data_in_len);
        break;
      case HALT:
        res = -2;
        break;
      default:
        res = -3;
    }
    return res;
}
``` my code is

**Comment by mywalkb** [comment]
Could you enabled debug in PN532/PN532_debug.h and post serial output? Just uncomment the define DEBUG.

**Comment by Tankonyako** [comment]
> Could you enabled debug in PN532/PN532_debug.h and post serial output? Just uncomment the define DEBUG.

tgInitAsTarget failed or timed out!-1
write:  08 63 03 80
read:   09
write:  08 63 02 80
read:   09
write:  32 01 00
read:   33
write:  06 63 38
read:   07 00
write:  08 63 38 00
read:   09
write:  06 63 0D
read:   07 00
write:  08 63 0D 00
read:   09
write:  06 63 05
read:   07 20
write:  08 63 05 24
read:   09
write:  12 10
read:   13
write:  8C 01 04 00 12 34 56 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
tgInitAsTarget failed or timed out!-1
write:  08 63 03 80
read:   09
write:  08 63 02 80
read:   09
write:  32 01 00
read:   33
write:  06 63 38
read:   07 00
write:  08 63 38 00
read:   09
write:  06 63 0D
read:   07 00
write:  08 63 0D 00
read:   09
write:  06 63 05
read:   07 20
write:  08 63 05 24
read:   09
write:  12 10
read:   13
write:  8C 01 04 00 12 34 56 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by Tankonyako** [comment]
it seems like android not trying communicate with tag i think

**Comment by mywalkb** [comment]
Rigth, but is strange, after the command write: 8C 01 04 00 12 34 56 00 00 00 00 .... the emulation wait 5 seconds and if a reader send data should be detect ed and see the comunication.
After the last write before timeout, you should see read 00 30 00 ( read command block 0x00) first 0x00 is the status.

Have you only one reader for test?

**Comment by Tankonyako** [comment]
Yes im have one reader.

**Comment by Tankonyako** [comment]
If you try my code, it will work? Im also was modify some headers because compiler giving errors with function invalid type arguments

**Comment by mywalkb** [comment]
Your code use SPI Software? In this period I can't test, I do not have pn532 with me. From your log there isn't issue with spi comunication. Registers are set correctly.

**Comment by Tankonyako** [comment]
Yes im using SPI. but im received new arduino and can test HSU

**Comment by Tankonyako** [comment]
im was use AI tinkerer with small pin count, but pn532 working with spi, like reading and emulating on phone (broken).
